const $=s=>document.querySelector(s),M=window.ClaimModel,KEY='claimdesk-prd-simple-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storageIssue='',claims;try{const s=JSON.parse(localStorage.getItem(KEY));claims=Array.isArray(s)&&s.length&&s.every(c=>M.STATUS[c.status]&&M.ROUTES[c.route]&&Array.isArray(c.audit)&&c.coverage&&c.facts)?s:M.fixtures().slice(0,3)}catch{claims=M.fixtures().slice(0,3);storageIssue='Saved demo data could not be loaded. Showing the original samples.'}
let currentId=null;
const pretty=s=>String(s).replace(/_/g,' ').replace(/^./,v=>v.toUpperCase());
const dateLabel=d=>d?new Date(d+'T12:00:00').toLocaleDateString('en-AU',{day:'2-digit',month:'short',year:'numeric'}):'Unknown';
const timeLabel=d=>new Date(d).toLocaleString('en-AU',{timeZone:'Australia/Melbourne',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false});
const money=v=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(v);
const percent=v=>typeof v==='number'?Math.round(v*100)+'%':'Unknown';
const tag=(text,tone='processing')=>`<span class="badge ${tone}">${esc(text)}</span>`;
const routeTag=c=>tag(M.ROUTES[c.route],{auto_path:'ready',human_review:'review',urgent:'urgent'}[c.route]);
const statusTag=c=>tag(M.STATUS[c.status],{decision_ready:'info',approved_next_stage:'ready',info_requested:'review'}[c.status]||'processing');
function persist(){try{localStorage.setItem(KEY,JSON.stringify(claims));storageIssue='';return true}catch{storageIssue='Browser storage is unavailable. Changes will last only until this page is refreshed.';return false}}
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),5000)}
function renderInbox(){
$('#claimCount').textContent=claims.length;$('#inboxError').textContent=storageIssue;
const activeRoute=$('#routeFilter').value;
$('#summaryCards').innerHTML=[['all','Total claims',claims.length,'All vehicle claims'],['auto_path','Standard path',claims.filter(c=>c.route==='auto_path').length,'Routed to the standard process'],['human_review','Human review',claims.filter(c=>c.route==='human_review').length,'Requires officer assessment'],['urgent','Urgent escalation',claims.filter(c=>c.route==='urgent').length,'Prioritise these vehicle cases']].map(([r,l,n,t])=>`<button class="summary-card ${r}" data-route-filter="${r}" aria-pressed="${activeRoute===r}"><span class="summary-label">${l}</span><strong>${n}</strong><span class="summary-foot">${t}</span></button>`).join('');
const search=$('#claimSearch').value.toLowerCase().trim(),status=$('#statusFilter').value;
const shown=claims.filter(c=>(activeRoute==='all'||c.route===activeRoute)&&(status==='all'||c.status===status)&&[c.id,c.policyId,c.vehicle,c.rego,c.name,c.location,c.incident,...c.riskFlags].some(v=>String(v||'').toLowerCase().includes(search))).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt));
$('#claimList').innerHTML=shown.map(c=>`<tr><td><a class="claim-id table-claim-link" href="${claimURL(c)}" data-nav>${esc(c.id)}</a><small>${esc(c.policyId)}</small></td><td><strong>${esc(c.vehicle)}</strong><small>${esc(c.rego)}</small></td><td>${esc(c.incident)}<small>${dateLabel(c.date)}</small></td><td>${statusTag(c)}</td><td>${routeTag(c)}</td><td><div class="table-flags">${c.riskFlags.length?c.riskFlags.map(f=>tag(pretty(f),'review')).join(''):'<span class="no-flags">None recorded</span>'}</div></td><td><time>${timeLabel(c.updatedAt)}</time><small>AEST</small></td><td><a class="open-case" href="${claimURL(c)}" data-nav aria-label="Open ${esc(c.id)}">Open →</a></td></tr>`).join('');
$('#noResults').hidden=shown.length!==0;$('#tableCount').textContent=`Showing ${shown.length} of ${claims.length} claims`;
}
function claimURL(c){return /^CLM-DEMO-[ABC]$|^CLM-2026-10(3[7-9]|4[0-5])$/.test(c.id)?'/claims/'+encodeURIComponent(c.id)+'/':'/claims/?claim='+encodeURIComponent(c.id)}
function navigate(path){history.pushState({},'',path);renderRoute();window.scrollTo({top:0,behavior:'instant'})}
function renderRoute(){const part=location.pathname.split('/').filter(Boolean);currentId=part[0]==='claims'&&part[1]?decodeURIComponent(part[1]):new URLSearchParams(location.search).get('claim');$('#inboxView').hidden=!!currentId;$('#caseView').hidden=!currentId;if(currentId)renderCase();renderInbox()}
function kv(label,value){return `<div class="kv"><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`}
function panel(number,title,body,cls=''){return `<section class="case-panel ${cls}"><div class="case-panel-title"><h2>${title}</h2></div>${body}</section>`}
const known=(v)=>v===true?'Yes':v===false?'No':v==null?'Unknown':String(v);
function findingHTML(f){return `<div class="finding"><div class="finding-title"><strong>${esc(pretty(f.area))}</strong>${tag(f.severity||'Unknown',f.severity||'unknown')}</div><p>${esc(f.observation)}</p><div class="finding-meta">${tag(f.source||'Unknown source')}<span>Confidence: ${percent(f.confidence)}</span></div></div>`}
function diagram(findings){
const severityRank={unknown:0,minor:1,moderate:2,severe:3};const zones=M.ZONES.map(z=>{const fs=findings.filter(f=>M.mapZone(f.area)===z);const severity=fs.length?fs.reduce((s,f)=>(severityRank[f.severity]??0)>(severityRank[s]??0)?f.severity:s,'unknown'):'neutral';return {z,fs,severity}});
const shapes={'front':'<path d="M89 39 Q130 21 171 39 L183 70 H77 Z"/>','rear':'<path d="M77 315 H183 L176 341 Q130 356 84 341 Z"/>','windscreen':'<path d="M88 111 H172 L165 153 H95 Z"/>','roof':'<rect x="96" y="163" width="68" height="96" rx="13"/>','left side':'<path d="M74 107 H85 L92 160 V272 L79 309 H69 Z"/>','right side':'<path d="M175 107 H186 L191 309 H181 L168 272 V160 Z"/>','left headlight':'<rect x="77" y="80" width="25" height="19" rx="6"/>','right headlight':'<rect x="158" y="80" width="25" height="19" rx="6"/>'};
return `<div class="damage-map"><div class="map-orientation">FRONT</div><svg class="car-svg" viewBox="0 0 260 375" role="group" aria-label="Top-down vehicle damage diagram"><path class="car-shell" d="M88 32 Q130 16 172 32 Q190 42 194 85 L201 309 Q198 350 170 356 H90 Q62 350 59 309 L66 85 Q70 42 88 32Z"/><g class="wheels"><rect x="48" y="91" width="12" height="49" rx="5"/><rect x="200" y="91" width="12" height="49" rx="5"/><rect x="47" y="275" width="12" height="43" rx="5"/><rect x="201" y="275" width="12" height="43" rx="5"/></g><path class="car-window" d="M95 271 H165 L175 303 H85 Z"/>${zones.map(({z,fs,severity})=>`<g class="car-zone ${severity}" ${fs.length?`role="button" tabindex="0" data-zone="${z}" aria-label="${esc(z+': '+fs.map(f=>f.observation).join(' '))}"`:''}><title>${esc(pretty(z))}: ${fs.length?esc(fs.map(f=>f.observation+' ('+f.source+')').join('; ')):'No mapped finding'}</title>${shapes[z]}</g>`).join('')}<text x="130" y="216" class="roof-label" text-anchor="middle">ROOF</text><text x="25" y="211" class="side-label">L</text><text x="230" y="211" class="side-label">R</text></svg><div class="map-orientation">REAR</div><div class="map-legend"><span><i class="minor"></i>Minor</span><span><i class="moderate"></i>Moderate</span><span><i class="severe"></i>Severe</span><span><i class="unknown"></i>Unknown</span></div><p class="map-help">Select a highlighted area to inspect its findings.</p><div id="zoneDetail" class="zone-detail" aria-live="polite">No area selected. Neutral areas have no mapped finding; they are not confirmed undamaged.</div></div>`}
function renderCase(){const c=claims.find(x=>x.id===currentId);if(!c){$('#caseView').innerHTML='<a data-nav href="/claims/" class="back-link">← Claims dashboard</a><h1>Claim not found</h1><p>This claim is not available in this browser’s demo data.</p>';return}
const ass=c.assessment,fs=ass?.findings||[],unplaced=fs.filter(f=>!M.mapZone(f.area));
const header=`<a href="/claims/" data-nav class="back-link">← Claims dashboard</a><section class="case-header"><div><div class="eyebrow">VEHICLE CASE · ${esc(c.id)}</div><h1>${esc(c.vehicle)}</h1><div class="case-subtitle"><strong>${esc(c.rego)}</strong><span>·</span><span>${esc(c.policyId||'Policy not captured')}</span><span>·</span><span>${esc(c.coverage.type||'Coverage unknown')}</span></div><div class="case-customer">${esc(c.name)} · ${esc(c.customerId)}<br>Created ${timeLabel(c.createdAt)} · Updated ${timeLabel(c.updatedAt)} AEST</div></div><div class="header-tags">${statusTag(c)}${routeTag(c)}</div></section>`;
const incident=panel('01','Incident',`<dl class="kv-grid">${kv('Incident date',dateLabel(c.date))}${c.location?kv('Location',c.location):''}${Object.entries(c.facts).filter(([k,v])=>v!=null&&!/injur|passenger|emergency|human|person/i.test(k)).map(([k,v])=>kv(pretty(k),known(v))).join('')}</dl><div class="narrative"><h3>Original vehicle account</h3><p>${esc(c.narrative)}</p></div>`);
const assessment=panel('02','Assessment',ass?`<div class="assessment-layout">${diagram(fs)}<div class="assessment-findings"><div class="estimate"><span class="eyebrow">PRELIMINARY REPAIR ESTIMATE · AUD</span><strong>${ass.estimate?money(ass.estimate.min)+' – '+money(ass.estimate.max):'Not yet established'}</strong><p>Suggested range only. Subject to inspection and a repairer quote.</p></div>${fs.filter(f=>M.mapZone(f.area)).map(findingHTML).join('')}${unplaced.length?`<div class="unplaced"><h3>Location not established <span>${unplaced.length}</span></h3><p>These findings cannot be placed on the vehicle without guessing.</p>${unplaced.map(findingHTML).join('')}</div>`:''}</div></div><div class="assessment-notes"><div><h3>Assumptions</h3>${ass.assumptions.length?`<ul>${ass.assumptions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>No assumptions recorded.</p>'}</div><div class="missing-info"><h3>Missing information</h3>${ass.missing.length?`<ul>${ass.missing.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>No missing information recorded.</p>'}</div></div>`:'<p class="panel-empty">No assessment yet.</p>','assessment-panel');
const coverage=panel('03','Coverage',`<dl class="kv-grid">${kv('Coverage type',c.coverage.type||'Unknown')}${kv('Excess (AUD)',c.coverage.excess==null?'Unknown':money(c.coverage.excess))}${kv('Policy status',c.coverage.status||'Unknown')}${kv('Policy period',c.coverage.start&&c.coverage.end?dateLabel(c.coverage.start)+' – '+dateLabel(c.coverage.end):'Unknown')}</dl><div class="coverage-check"><h3>Preliminary coverage check ${tag(pretty(c.coverage.result||'Unknown'),c.coverage.result==='pass'?'ready':c.coverage.result==='fail'?'urgent':'review')}</h3><p>${esc(c.coverage.notes)}</p>${c.coverage.rules.map(r=>`<blockquote>${esc(r.text)}<small>${esc(r.id)}</small></blockquote>`).join('')}</div>`);
const risk=panel('04','Risk & uncertainty',`<div class="risk-flags">${c.riskFlags.length?c.riskFlags.map(f=>tag(pretty(f),c.route==='urgent'?'urgent':'review')).join(''):'<p class="muted">No vehicle risk flags recorded.</p>'}</div><dl class="kv-grid">${kv('Assessment confidence',percent(c.confidence))}${kv('Conflicting accounts',known(c.conflictingAccounts))}</dl><div class="route-reason"><h3>Route reason</h3><p>${esc(c.routeReason)}</p></div>`);
const evidence=panel('05','Evidence',c.evidence.length?`<div class="evidence-grid">${c.evidence.map(e=>`<article class="evidence-card">${e.src&&/^image\/(jpeg|png|webp|gif)$/.test(e.mime)?`<button class="evidence-image" data-image="${esc(e.src)}" aria-label="Enlarge ${esc(e.filename)}"><img src="${esc(e.src)}" alt="${esc(e.filename)}"></button>`:`<div class="evidence-placeholder"><span>▧</span><strong>${esc(e.mime)}</strong><small>Original file unavailable</small></div>`}<div class="evidence-caption"><h3>${esc(e.filename)}</h3><small>${timeLabel(e.uploadedAt)} AEST</small>${tag('Confidence: '+percent(e.confidence))}${e.limitations?`<p>${esc(e.limitations)}</p>`:''}</div></article>`).join('')}</div>`:'<p class="panel-empty">No evidence uploaded yet.</p>');
const recommendation=panel('06','Recommended action',`<p class="recommendation-text">${esc(c.recommendation)}</p><p class="non-binding">Non-binding — preliminary system suggestion only.</p>`,'recommendation-panel');
const actions=panel('07','Actions',`<div class="actions-top"><p>Move this vehicle claim to its next stage. Approval is not a final repair or coverage decision.</p></div><label class="action-note-label" for="actionNote">Note for information requests or escalation</label><textarea id="actionNote" rows="2" maxlength="2000" placeholder="Specify missing vehicle evidence or explain why this needs escalation…"></textarea><div class="action-buttons"><button class="primary" data-action="approve_next_stage" ${c.status==='approved_next_stage'?'disabled':''}>✓ Approve next stage</button><button class="secondary" data-action="request_information">Request information</button><button class="secondary danger-button" data-action="escalate">Escalate</button><button class="secondary" id="overrideToggle" aria-expanded="false" aria-controls="overrideFields">Override ⌄</button></div><div class="override-fields" id="overrideFields" hidden><label>Status<select id="overrideStatus"><option value="">Keep current status</option>${Object.entries(M.STATUS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>Route<select id="overrideRoute"><option value="">Keep current route</option>${Object.entries(M.ROUTES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><button class="secondary" id="applyOverride" data-action="override" disabled>Apply override</button></div><p id="actionError" class="inline-error" role="alert"></p>${storageIssue?`<p class="inline-error">${esc(storageIssue)}</p>`:''}`,'full-span actions-panel');
const audit=panel('08','Audit',c.audit.length?`<div class="audit-list">${[...c.audit].sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp)).map(e=>`<div class="audit-event"><time>${timeLabel(e.timestamp)} AEST</time>${tag(e.actor)}<div><strong>${esc(pretty(e.action))}</strong><p>${esc(e.result)}</p></div></div>`).join('')}</div>`:'<p class="panel-empty">No audit events yet.</p>','full-span');
$('#caseView').innerHTML=header+`<div class="case-grid"><div class="case-column">${incident}${coverage}${evidence}</div><div class="case-column">${assessment}${risk}${recommendation}</div>${actions}${audit}</div>`;
}
function showZone(zone){const c=claims.find(x=>x.id===currentId);const fs=c?.assessment?.findings.filter(f=>M.mapZone(f.area)===zone)||[];if($('#zoneDetail'))$('#zoneDetail').innerHTML=`<strong>${esc(pretty(zone))}</strong>${fs.map(f=>`<p>${esc(f.observation)}</p><small>Source: ${esc(f.source)} · Confidence: ${percent(f.confidence)}</small>`).join('')}`}
function performAction(action){const index=claims.findIndex(c=>c.id===currentId);try{const updated=M.applyAction(claims[index],action,$('#actionNote').value,{status:$('#overrideStatus').value,route:$('#overrideRoute').value});claims[index]=updated;persist();renderCase();renderInbox();toast(storageIssue||'Claim updated. Officer action added to the audit trail.')}catch(e){$('#actionError').textContent=e.message}}
document.addEventListener('click',e=>{const nav=e.target.closest('a[data-nav]');if(nav&&!e.metaKey&&!e.ctrlKey&&!e.shiftKey){e.preventDefault();navigate(nav.getAttribute('href'));return}const zone=e.target.closest('[data-zone]');if(zone)showZone(zone.dataset.zone);const a=e.target.closest('[data-action]');if(a)performAction(a.dataset.action);if(e.target.closest('#overrideToggle')){const field=$('#overrideFields');field.hidden=!field.hidden;$('#overrideToggle').setAttribute('aria-expanded',!field.hidden)}});
document.addEventListener('change',e=>{if(['overrideStatus','overrideRoute'].includes(e.target.id))$('#applyOverride').disabled=!($('#overrideStatus').value||$('#overrideRoute').value)});
document.addEventListener('keydown',e=>{const z=e.target.closest('[data-zone]');if(z&&['Enter',' '].includes(e.key)){e.preventDefault();showZone(z.dataset.zone)}});
$('#statusFilter').innerHTML='<option value="all">All statuses</option>'+Object.entries(M.STATUS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');
$('#claimSearch').addEventListener('input',renderInbox);$('#statusFilter').addEventListener('change',renderInbox);$('#routeFilter').addEventListener('change',renderInbox);
$('#clearFilters').addEventListener('click',()=>{$('#claimSearch').value='';$('#statusFilter').value='all';$('#routeFilter').value='all';renderInbox()});
document.addEventListener('click',e=>{const card=e.target.closest('[data-route-filter]');if(card){$('#routeFilter').value=card.dataset.routeFilter;renderInbox()}});
window.addEventListener('popstate',renderRoute);renderRoute();
