(function(root){
const STATUS={intake:'Intake',awaiting_evidence:'Awaiting evidence',decision_ready:'Decision ready',approved_next_stage:'Approved next stage',info_requested:'Information requested',closed:'Closed'};
const ROUTES={auto_path:'Standard path',human_review:'Human review',urgent:'Urgent escalation'};
const ZONES=['front','rear','left side','right side','windscreen','roof','left headlight','right headlight'];
function mapZone(area){const a=String(area||'').toLowerCase();const left=/\bleft\b/.test(a),right=/\bright\b/.test(a);if(/\b(headlight|headlights|light cluster)\b/.test(a))return left&&!right?'left headlight':right&&!left?'right headlight':null;if(/\b(windscreen|windshield)\b/.test(a))return 'windscreen';if(/\bglass\b/.test(a))return /\b(rear|side|door|window)\b/.test(a)?null:'windscreen';if(/\broof\b/.test(a))return 'roof';if(/\b(door|doors|side|side panel)\b/.test(a))return left&&!right?'left side':right&&!left?'right side':null;const front=/\b(front|grille)\b/.test(a)||(/\bbumper\b/.test(a)&&/\b(hood|bonnet)\b/.test(a));const rear=/\b(rear|taillight|taillights)\b/.test(a)||(/\bbumper\b/.test(a)&&/\b(boot|trunk)\b/.test(a));return front&&!rear?'front':rear&&!front?'rear':null}
const stamp='2026-09-12T04:10:00Z';
function base(id,name,vehicle,rego,route,order){return{id,name,vehicle,rego,route,order,status:'decision_ready',priority:route==='urgent'?'High':route==='human_review'?'Medium':'Low',policyId:'POL-'+(1000+order),customerId:'CUST-'+name.split(' ')[0].toUpperCase(),incident:'Collision',date:'2026-09-12',createdAt:'2026-09-12T03:50:00Z',updatedAt:new Date(Date.parse(stamp)-order*60000).toISOString(),location:null,narrative:'Vehicle damage reported. Further incident details have not been captured in this sample.',facts:{incident_type:'Collision',vehicle_drivable:null,airbags_deployed:null,weather:null,other_vehicles:null},coverage:{type:'Comprehensive',excess:850,status:'Active',start:'2026-01-01',end:'2026-12-31',result:'needs_review',notes:'The available sample information has not yet been checked against coverage.',rules:[]},assessment:null,evidence:[],riskFlags:[],confidence:null,conflictingAccounts:null,routeReason:'Awaiting assessment of the vehicle claim.',recommendation:'Review available vehicle evidence and confirm missing details.',audit:[{timestamp:'2026-09-12T03:50:00Z',actor:'system',action:'claim_created',result:'Fictional claim loaded into the demo workspace.'}]}}
function fixtures(){
const a=base('CLM-DEMO-A','Maya Chen','2022 Mazda 3','MCH 219','auto_path',1);Object.assign(a,{location:'George Street, Melbourne VIC',narrative:'The vehicle was parked on George Street when another vehicle contacted the rear bumper. The bumper is dented and the paint is scratched. The vehicle can still be driven.',facts:{incident_type:'Parked damage',vehicle_drivable:true,airbags_deployed:false,weather:'Dry',other_vehicles:1},incident:'Parked damage',conflictingAccounts:false,confidence:0.91,routeReason:'Sample evidence supports localised rear damage. No vehicle escalation flag is recorded.',recommendation:'Approve the next stage to obtain a repairer quote for the rear bumper. Confirm the location of the paintwork damage.'});a.coverage={...a.coverage,result:'pass',notes:'The sample incident date and insured vehicle match the demonstration policy.',rules:[{id:'DEMO-MOTOR-01',text:'Demo rule: accidental damage to the listed vehicle is covered during the policy period, subject to the policy terms and excess.'}]};a.assessment={estimate:{min:1200,max:2200},findings:[{area:'rear bumper',severity:'moderate',observation:'Localised dent and surface abrasion visible in the sample assessment.',source:'vision',confidence:0.93},{area:'paintwork',severity:'minor',observation:'Scratched paint reported, but the location is not specified.',source:'customer',confidence:null}],assumptions:['Damage is limited to the exterior bumper; hidden damage has not been assessed.'],missing:['Confirm where the paintwork is scratched.']};a.evidence=[{filename:'rear-bumper.jpg',mime:'image/jpeg',uploadedAt:'2026-09-12T03:55:00Z',confidence:0.93,limitations:'Demo record only. Original photo bytes were not supplied with the brief.',src:null},{filename:'vehicle-statement.pdf',mime:'application/pdf',uploadedAt:'2026-09-12T03:56:00Z',confidence:null,limitations:'Document contents are unavailable in this prototype.',src:null}];a.audit.push({timestamp:'2026-09-12T04:01:00Z',actor:'AI',action:'evidence_analysed',result:'Demo result: rear bumper finding recorded; paintwork left unplaced.'},{timestamp:'2026-09-12T04:04:00Z',actor:'system',action:'coverage_checked',result:'Preliminary sample coverage check passed.'},{timestamp:a.updatedAt,actor:'system',action:'claim_routed',result:'Vehicle case prepared for standard path.'});
const b=base('CLM-DEMO-B',"Liam O’Brien",'2024 Ford Ranger','DFR 872','human_review',2);Object.assign(b,{location:'Footscray, Melbourne VIC',narrative:'A side panel was damaged during a collision. The account describes a parked vehicle, while the sample evidence notes possible movement at impact. The affected side has not been established.',conflictingAccounts:true,riskFlags:['conflicting_accounts','damage_location_unclear'],confidence:0.63,routeReason:'Conflicting accounts and an unspecified side prevent a confident vehicle assessment.',recommendation:'Request the affected side and additional vehicle photographs. Resolve the conflicting accounts before progressing.'});b.assessment={estimate:{min:1800,max:4200},findings:[{area:'side panel',severity:'moderate',observation:'A dented side panel is described. Left or right is not specified.',source:'heuristic',confidence:0.63}],assumptions:['Estimate assumes repairable exterior sheet metal.'],missing:['Identify the left or right side.','Obtain wider-angle vehicle photographs.','Clarify whether the vehicle was moving.']};b.evidence=[{filename:'side-panel.jpg',mime:'image/jpeg',uploadedAt:'2026-09-12T03:57:00Z',confidence:0.63,limitations:'Filename-based sample finding; no original photo bytes are available.',src:null}];b.audit.push({timestamp:b.updatedAt,actor:'system',action:'human_review_triggered',result:'Conflicting vehicle accounts and uncertain damage location require review.'});
const c=base('CLM-DEMO-C','Priya Nair','2024 Toyota Corolla','ABC 123','urgent',3);Object.assign(c,{location:'Kings Way, Melbourne VIC',narrative:'A substantial front impact has damaged the front section and right headlight. The vehicle cannot be driven. This vehicle-only demonstration requires a tow and an inspection for possible hidden structural damage.',facts:{incident_type:'Collision',vehicle_drivable:false,airbags_deployed:true,weather:null,other_vehicles:1},riskFlags:['vehicle_not_drivable','possible_structural_damage','airbags_deployed'],confidence:0.78,routeReason:'The vehicle is not drivable and potential structural damage requires urgent vehicle assessment.',recommendation:'Escalate for towing and a qualified vehicle inspection before any repair approval.'});c.assessment={estimate:null,findings:[{area:'front bumper and bonnet',severity:'severe',observation:'Significant front deformation is recorded in the simulated assessment. Structural damage is possible but unconfirmed.',source:'vision',confidence:0.82},{area:'right headlight',severity:'moderate',observation:'Right headlight housing appears damaged in the sample finding.',source:'vision',confidence:0.78}],assumptions:['The extent of internal damage remains unknown.'],missing:['Qualified structural inspection.','Repairer estimate after inspection.']};c.evidence=[{filename:'front-impact.jpg',mime:'image/jpeg',uploadedAt:'2026-09-12T03:58:00Z',confidence:0.82,limitations:'Demo analysis only. No source photograph was supplied.',src:null}];c.audit.push({timestamp:c.updatedAt,actor:'system',action:'vehicle_escalation_triggered',result:'Vehicle immobilisation and possible structural damage triggered the urgent route.'});
return[a,b,c]}
function applyAction(claim,action,note,override={},timestamp=new Date().toISOString()){
const c=JSON.parse(JSON.stringify(claim));let result;
if(action==='approve_next_stage'){c.status='approved_next_stage';result='Officer approved the next workflow stage. This does not approve a repair cost or final coverage.'}
else if(action==='request_information'){if(!note.trim())throw new Error('Add a note describing the information required.');c.status='info_requested';result='Information requested: '+note.trim()}
else if(action==='escalate'){if(!note.trim())throw new Error('Add a reason for escalation.');c.route=c.priority==='High'||c.route==='urgent'?'urgent':'human_review';c.riskFlags=[...new Set([...c.riskFlags,'officer_escalated'])];c.routeReason=note.trim();result='Escalated to '+ROUTES[c.route]+': '+note.trim()}
else if(action==='override'){if(!override.status&&!override.route)throw new Error('Choose a status or route to override.');if(override.status){if(!STATUS[override.status])throw new Error('Unknown status.');c.status=override.status}if(override.route){if(!ROUTES[override.route])throw new Error('Unknown route.');c.route=override.route;c.routeReason='Route manually selected by the officer.'}result='Officer override: '+[override.status&&STATUS[override.status],override.route&&ROUTES[override.route]].filter(Boolean).join(' / ')}else throw new Error('Unknown action.');c.updatedAt=timestamp;c.audit.unshift({timestamp,actor:'officer',action,result});return c
}
root.ClaimModel={STATUS,ROUTES,ZONES,mapZone,fixtures,applyAction,base};
})(typeof window==='undefined'?globalThis:window);
